name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - numpy
      - joblib
      - matplotlib
      - seaborn
